module.exports = {
  testEnvironment: 'node',
  clearMocks: true,
  coverageDirectory: 'coverage',
  collectCoverageFrom: ['src/**/*.*', '!**/node_modules/**', '!**/vendor/**', '!**/dist/**'],
  coveragePathIgnorePatterns: [
    'node_modules',
    'coverage',
    'src/server.js',
    'src/app.js',
    'src/cron-jobs',
    'src/helpers/logger.js',
    'src/helpers',
    'src/scripts',
    'src/services',
    'src/middlewares/joiErrors.js',
    'src/middlewares/asyncHandler.js',
    'src/config',
    'src/constants',
    'src/resources/api/v3/swagger',
    'src/database',
    'src/backup',
    'src/resources/api/v3/swagger',
  ],
  testPathIgnorePatterns: ['<rootDir>/dist/'],
  verbose: true,
  coverageThreshold: {
    global: {
      functions: 0,
      lines: 0,
      statements: -10000,
    },
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  testMatch: ['**/__tests__/**/*.(spec|test).js?(x)'],
  transform: {
    '^.+\\.ts?$': 'babel-jest',
    '^.+\\.(js|jsx)?$': 'babel-jest',
  },
  setupFilesAfterEnv: ['./jest.setup.js'],
  coverageReporters: ['html', 'text', 'text-summary', 'cobertura'],
};
